name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Install backend dependencies (Node.js)
        run: |
          cd backend/node
          npm install

      - name: Install backend dependencies (Django)
        run: |
          cd backend/django
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install backend dependencies (Flask)
        run: |
          cd backend/flask
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Run backend tests (Node.js)
        run: |
          cd backend/node
          npm test

      - name: Run backend tests (Django)
        run: |
          cd backend/django
          source venv/bin/activate
          python manage.py test

      - name: Run backend tests (Flask)
        run: |
          cd backend/flask
          source venv/bin/activate
          python -m unittest discover
