name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r backend/django/Opus/requirements.txt
    - name: Run tests
      run: |
        source venv/bin/activate
        python backend/django/Opus/manage.py test
